### ISSUE TITLE
Pixel 6 Pro Android 14 Beta 3 无法使用

### ISSUE THREAD

**Issue by Cyl18** [dantmnf/PseudoDCDimming#3]
Android 14 Beta 3
LSPosed 1.8.6

```log
[ 2023-07-08T07:46:04.036     1000:  1358:  1837 E/LSPosed-Bridge  ] java.lang.NoSuchMethodError: No static method getStaticDisplayInfo(Landroid/os/IBinder;)Landroid/view/SurfaceControl$StaticDisplayInfo; in class Landroid/view/SurfaceControl; or its super classes (declaration of 'android.view.SurfaceControl' appears in /system/framework/framework.jar!classes4.dex)
	at xyz.cirno.pseudodcdimming.xposed.XposedInit$2.afterHookedMethod(XposedInit.java:84)
	at de.robv.android.xposed.XposedBridge$AdditionalHookInfo.callback(Unknown Source:175)
	at LSPHooker_.constructor(Unknown Source:21)
	at com.android.server.display.LocalDisplayAdapter$LocalDisplayDevice.<init>(LocalDisplayAdapter.java:248)
	at java.lang.reflect.Method.invoke(Native Method)
	at org.lsposed.lspd.nativebridge.HookBridge.invokeOriginalMethod(Native Method)
	at de.robv.android.xposed.XposedBridge$AdditionalHookInfo.callback(Unknown Source:132)
	at LSPHooker_.constructor(Unknown Source:38)
	at com.android.server.display.LocalDisplayAdapter.tryConnectDisplayLocked(LocalDisplayAdapter.java:152)
	at com.android.server.display.LocalDisplayAdapter.registerLocked(LocalDisplayAdapter.java:108)
	at com.android.server.display.DisplayManagerService.registerDisplayAdapterLocked(DisplayManagerService.java:1779)
	at com.android.server.display.DisplayManagerService.registerDefaultDisplayAdapters(DisplayManagerService.java:1729)
	at com.android.server.display.DisplayManagerService.-$$Nest$mregisterDefaultDisplayAdapters(DisplayManagerService.java:0)
	at com.android.server.display.DisplayManagerService$DisplayManagerHandler.handleMessage(DisplayManagerService.java:3201)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loopOnce(Looper.java:205)
	at android.os.Looper.loop(Looper.java:294)
	at android.os.HandlerThread.run(HandlerThread.java:67)
	at com.android.server.ServiceThread.run(ServiceThread.java:46)

```

[LSPosed_2023-07-08T07_53_58.173253.zip](https://github.com/dantmnf/PseudoDCDimming/files/11986938/LSPosed_2023-07-08T07_53_58.173253.zip)

**Comment by dantmnf** [comment]
try [this build](https://github.com/dantmnf/PseudoDCDimming/files/11987206/app-release.zip)

**Comment by Cyl18** [comment]
新的问题：

```
java.lang.NoSuchMethodError: No static method getPhysicalDisplayIds()[J in class Landroid/view/SurfaceControl; or its super classes (declaration of 'android.view.SurfaceControl' appears in /system/framework/framework.jar!classes4.dex)
	at xyz.cirno.pseudodcdimming.xposed.SurfaceControlCompat.getStaticDisplayInfo(SurfaceControlCompat.java:13)
	at xyz.cirno.pseudodcdimming.xposed.XposedInit$2.afterHookedMethod(XposedInit.java:84)
	at de.robv.android.xposed.XposedBridge$AdditionalHookInfo.callback(Unknown Source:175)
	at LSPHooker_.constructor(Unknown Source:21)
	at com.android.server.display.LocalDisplayAdapter$LocalDisplayDevice.<init>(LocalDisplayAdapter.java:248)
	at java.lang.reflect.Method.invoke(Native Method)
	at org.lsposed.lspd.nativebridge.HookBridge.invokeOriginalMethod(Native Method)
	at de.robv.android.xposed.XposedBridge$AdditionalHookInfo.callback(Unknown Source:132)
	at LSPHooker_.constructor(Unknown Source:38)
	at com.android.server.display.LocalDisplayAdapter.tryConnectDisplayLocked(LocalDisplayAdapter.java:152)
	at com.android.server.display.LocalDisplayAdapter.registerLocked(LocalDisplayAdapter.java:108)
	at com.android.server.display.DisplayManagerService.registerDisplayAdapterLocked(DisplayManagerService.java:1779)
	at com.android.server.display.DisplayManagerService.registerDefaultDisplayAdapters(DisplayManagerService.java:1729)
	at com.android.server.display.DisplayManagerService.-$$Nest$mregisterDefaultDisplayAdapters(DisplayManagerService.java:0)
	at com.android.server.display.DisplayManagerService$DisplayManagerHandler.handleMessage(DisplayManagerService.java:3201)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loopOnce(Looper.java:205)
	at android.os.Looper.loop(Looper.java:294)
	at android.os.HandlerThread.run(HandlerThread.java:67)
	at com.android.server.ServiceThread.run(ServiceThread.java:46)
```

**Comment by dantmnf** [comment]
try [this build](https://github.com/dantmnf/PseudoDCDimming/files/11987282/app-release.zip)

**Comment by Cyl18** [comment]
> try [this build](https://github.com/dantmnf/PseudoDCDimming/files/11987282/app-release.zip)

solved, thanks👍
